version: "3.8"

services:
  postgres1:
    container_name: postgresql_db1
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgresql_db1
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=bruh@email.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5050:80
